# PNPM aliases
alias pi="pnpm install"
alias pa="pnpm add"
alias pad="pnpm add -D"
alias prm="pnpm remove"
alias pls="pnpm list"
alias prun="pnpm run"
alias pdev="pnpm run dev"
alias pbuild="pnpm run build"
alias pstart="pnpm run start"
alias ptest="pnpm run test"
alias pdx="pnpm dlx"
alias pupdate="pnpm update"
alias pupgrade="pnpm update -i"

# Project-specific PNPM aliases
alias qd="pnpm exec turbo run dev --filter=quantum"
alias qs="pnpm --filter=quantum start"
alias qb="pnpm exec turbo run build --filter=quantum"
alias qc="pnpm --filter=quantum check" 