# Brewfile for managing dependencies
# Usage: brew bundle install

# Taps
tap "homebrew/bundle"

# Shell tools
brew "zsh"
brew "fzf"
brew "zoxide"
brew "starship"
brew "atuin"
brew "thefuck"
brew "diff-so-fancy"
brew "gh"
brew "hub"
brew "ripgrep"
brew "bat"
brew "eza"
brew "fd"

# Development tools
brew "git"
brew "node"
brew "yarn"
brew "pnpm"
brew "bun"
brew "python"
brew "pipx"
brew "docker"
brew "docker-compose"

# Fonts
cask "font-fira-code"
cask "font-jetbrains-mono"
cask "font-hack-nerd-font"

# Applications
cask "visual-studio-code"
cask "iterm2"
cask "rectangle"
cask "alfred"

# Comment out any packages you don't want to install
# Add any additional packages you need 