# Starship Configuration - Enhanced Setup
# See https://starship.rs/config/ for more options

# Use a single line prompt
add_newline = false

# Minimal format with essential modules
format = """
$directory\
$git_branch\
$git_status\
$character"""

# Directory configuration - improved
[directory]
truncation_length = 5  # Increased from 3 to 5 for better context
truncate_to_repo = true
style = "blue bold"
home_symbol = "~"  # Clear home symbol
read_only = " 󰌾"  # Nerd Font lock symbol for read-only directories

# Git branch configuration - minimal
[git_branch]
format = "[$branch]($style) "
style = "purple"
symbol = ""

# Git status - simplified and minimal
[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "yellow"
conflicted = "="
ahead = "↑"
behind = "↓"
diverged = "↕"
untracked = "?"
stashed = "s"
modified = "!"
staged = "+"
renamed = "r"
deleted = "x"

# Command duration - now included in format
[cmd_duration]
min_time = 2000  # Only show for commands that take more than 2 seconds
format = "took [$duration]($style) "
style = "yellow"

# Character prompt - minimal
[character]
success_symbol = "[>](green)"
error_symbol = "[>](red)"

# Shell configuration - now included in format
[shell]
disabled = false
format = "[$indicator]($style) "
bash_indicator = "bash"
zsh_indicator = "zsh"
fish_indicator = "fish"
powershell_indicator = "pwsh"
unknown_indicator = "shell"
style = "cyan bold"

# Time module
[time]
disabled = false
format = '[$time]($style) '
time_format = "%H:%M:%S"
style = "bold yellow"

# Language and environment modules
[nodejs]
format = "[$symbol$version](green bold) "
symbol = " 󰎙 "
detect_extensions = ["js", "jsx", "ts", "tsx", "mjs", "cjs"]

[python]
format = "[$symbol$version( \\($virtualenv\\))]($style) "
symbol = " 󰌠 "
style = "yellow bold"
detect_extensions = ["py", "pyc", "pyd"]
python_binary = ["python", "python3", "python2"]

[rust]
format = "[$symbol$version]($style) "
symbol = " 󱘗 "
style = "red bold"

[docker_context]
symbol = " 󰡨 "

[package]
symbol = " 󰏗 "

# Performance optimization
command_timeout = 500

# Optional Powerline-style segments
# Uncomment these if you want to use Powerline style
# (requires proper font support)
# [aws]
# format = 'on [$symbol$profile(\($region\))]($style) '
# style = "bold blue"
# symbol = "󰸏 "

# [kubernetes]
# format = 'on [󱃾 $context\($namespace\)]($style) '
# style = "bold purple" 